#!/usr/bin/env php

<?php

use Versyx\Codepad\Console\Jailer;

require __DIR__ . '/../config/bootstrap.php';

run($app['jailer'], getopt('', ['jail::', 'version:', 'first-run::']));

/**
 * Jail builder method.
 * 
 * @param Jailer $jailer
 * @param string $version
 */
function run(Jailer $jailer, array $opts)
{
    if(!$jail = env("JAIL_ROOT")) {
        $jail = $opts['jail'] ?? error('You must specify a root path.');
    }

    $jailer->setRoot($jail);

    if(env("JAIL_DEVICES")) {
        $jailer->setDevices(explode(',', env("JAIL_DEVICES")));
    } else {
        $jailer->setDevices(['bin','dev','etc','lib','lib64','usr']);
    }

    if(!$version = env("JAIL_PHP_VERSION")) {
        $version = $opts['version'] ?? error('You must specify a version.');
    }

    $php = '/php-' . $version;

    $jailer->buildJail($version);

    if(isset($opts['first-run'])) {
        $jailer->setPermissions(0711);
        $jailer->setOwnership('root', 'root');
        $jailer->mountAll();
    }
    
    $jailer->mkJailDir($php);
    $jailer->mount('/tmp' . $php, $jailer->getRoot() . $php, 'bind', 'ro');
}

