#!/usr/bin/env php

<?php

use Versyx\Codepad\Console\Jailer;

require __DIR__ . '/../config/bootstrap.php';

if(!isset($argv[1])) {
    die('You must specify a PHP version.' . PHP_EOL);
}

$short = 'j::v:';
$long  = ['jail::', 'version:', 'first-run::'];
$opts  = getopt($short, $long);

run($app['jailer'], $opts);

/**
 * Jail builder method.
 * 
 * @param Jailer $jailer
 * @param string $version
 */
function run(Jailer $jailer, array $opts)
{
    if(!$jail = env("JAIL_ROOT")) {
        $jail = $opts['jail'] ?? $opts['j'];
    }

    if(!$version = env("JAIL_PHP_VERSION")) {
        $version = $opts['version'] ?? $opts['v'];
    }

    if(env("JAIL_DEVICES")) {
        $jailer->setDevices(explode(',', env("JAIL_DEVICES")));
    } else {
        $jailer->setDevices(['bin','dev','etc','lib','lib64','usr']);
    }

    if($jail) {
        $jailer->setRoot($jail);
    } else {
        echo 'You must set a root path.' . PHP_EOL;
        exit;
    }

    if($version) {
        $php = '/php-' . $version;

        $jailer->buildJail($version);

        if(isset($opts['first-run'])) {
            $jailer->setPermissions(0711);
            $jailer->setOwnership('root', 'root');
            $jailer->mountAll();
        }
        
        $jailer->mkJailDir($php);
        $jailer->mount('/tmp' . $php, $jailer->getRoot() . $php, 'bind', 'ro');
    } else {
        echo 'You must set a version.' . PHP_EOL;
        exit;
    }
}

