#!/usr/bin/env php

<?php

use Versyx\Codepad\Cli\Compiler;
use Versyx\Codepad\Cli\Downloader;

require __DIR__ . '/../config/bootstrap.php';

if(!isset($argv[1])) {
    die("You must specify a PHP version.");
}

$short = 'v:d:';
$long  = ['version:', 'debug:'];
$opts  = getopt($short, $long);

run(
    new Downloader($opts['debug'] ?? $opts['d']),
    new Compiler($opts['debug'] ?? $opts['d']),
    $opts['version'] ?? $opts['v']
);

/**
 * download/compile test method.
 *
 * @param Downloader $downloader
 * @param Compiler $compiler
 * @param string $version
 */
function run(Downloader $downloader, Compiler $compiler, string $version)
{
    try {
        $php = $downloader->setVersion($version)->download();
        $compiler->compile($php->getVersion(), $php->getTarget());
    } catch (\Exception $e) {
        echo $e->getMessage();
    }
}
