#!/usr/bin/env php

<?php

use Versyx\Codepad\Console\Compiler;
use Versyx\Codepad\Console\Downloader;

require __DIR__ . '/../config/bootstrap.php';

run($app['downloader'], $app['compiler'], getopt('', ['version:']));

/**
 * download/compile test method.
 *
 * @param Downloader $downloader
 * @param Compiler $compiler
 * @param array $opts
 */
function run(Downloader $downloader, Compiler $compiler, array $opts)
{
    if(!$version = env("CHROOT_PHP_VERSION")) {
        $version = $opts['version'] ?? error('You must specify a version.');
    }
    
    try {
        $php = $downloader->setVersion($version)->download();
        $compiler->compile($php->getVersion(), $php->getTarget());
    } catch (\Exception $e) {
        echo $e->getMessage();
        exit;
    }
}
