#!/usr/bin/env php

<?php

use Versyx\Codepad\Console\Compiler;
use Versyx\Codepad\Console\Downloader;

require __DIR__ . '/../config/bootstrap.php';

if(!isset($argv[1])) {
    die("You must specify a PHP version.");
}

$short = 'v:';
$long  = ['version:'];
$opts  = getopt($short, $long);

run($app['downloader'], $app['compiler'], $opts);

/**
 * download/compile test method.
 *
 * @param Downloader $downloader
 * @param Compiler $compiler
 * @param array $opts
 */
function run(Downloader $downloader, Compiler $compiler, array $opts)
{
    if(!$version = env("JAIL_PHP_VERSION")) {
        $version = $opts['version'] ?? $opts['v'];
    }
    
    try {
        $php = $downloader->setVersion($version)->download();
        $compiler->compile($php->getVersion(), $php->getTarget());
    } catch (\Exception $e) {
        echo $e->getMessage();
    }
}
